### ISSUE TITLE
Model's Meta ordering field added when using group_by

### ISSUE THREAD

**Issue by squio** [ra-systems/django-slick-reporting#10]
Use case: simple report for model grouped by one to many foreign key related model as in the [Group By Report](https://django-slick-reporting.readthedocs.io/en/latest/tour.html#group-by-report) example.

Code example; Groups have many Sessions through a ForeignKey relation in Session.

Session:
```py
class Session(model.Model):

    group = models.ForeignKey(
        'my_app.Group',
        blank=True, null=True,
        on_delete=models.PROTECT)
    start_time = models.FloatField(
        null=True, verbose_name=_('Start time'), db_index=True)
    created_at = models.DateTimeField(
        null=True, verbose_name=_('Created at'))

    # ...
    class Meta:
        db_table = 'myapp_session'
        ordering = ['-start_time']

```

In my reports configuration:
```py
class TotalSessions(SlickReportView):
    """ Sessions per group """

    report_model = Session
    date_field = 'created_at'
    group_by = 'group'
    columns = [
        'name',
        SlickReportField.create(Sum, 'distance', name='sum__distance'),
        SlickReportField.create(Sum, 'duration', name='sum__duration'),
    ]
```

Now my reports don't show the correct aggregate data but rather just the values for one group session.

The generated SQL from the debugger shows why: the field `start_time` from `Session._meta['ordering']` is added to the `group_by` clause:

```sql
SELECT `myapp_session`.`group_id`,
       SUM(`myapp_session`.`distance`) AS `distance__sum`
  FROM `myapp_session`
 WHERE (`myapp_session`.`created_at` > '2019-12-31 23:00:00' AND `myapp_session`.`created_at` <= '2020-12-31 23:00:00')
 GROUP BY `myapp_session`.`group_id`,
       `myapp_session`.`start_time`
``` 
Removing the field `ordering` in Session class Meta removes the extra group_by field from the SQL query and gives the correct results.

I'm not sure where to look for this issue, the word 'ordering' does not occur in the django-slick-reporting source anywhere!?

**Comment by RamezIssac** [comment]
Thank you for the comprehensive issue report !
Issue addressed on `develop` branch 

> I'm not sure where to look for this issue, the word 'ordering' does not occur in the django-slick-reporting source anywhere!?
Yeah order by is not mentioned, now it is mentioned to disable the initial order_by that might be on a model :)
