### ISSUE TITLE
TemplateDoesNotExist: slick_reporting/simple_report.html with Pipenv install

### ISSUE THREAD

**Issue by Chocrates** [ra-systems/django-slick-reporting#16]
👋 Hey all,

Getting the above error when doing a Pipenv install.   Looks like I am using version `0.5.0`.
I am not sure where the slick_reporting templates are supposed to be in my project, but I do see them in my site_packages folder

```
$ tree lib/python3.9/site-packages/slick_reporting/templates
lib/python3.9/site-packages/slick_reporting/templates
└── slick_reporting
    ├── base.html
    ├── simple_report.html
    └── table.html
```

Would copying the `slick_reporting` folder into my local templates be a quick workaround?

**Comment by Chocrates** [comment]
Steps that eventually got it working with pipenv:
1. `pipenv install django-slick-reporting`
1. `pipenv install django-crispy-forms`
1. Add 'slick_reporting' to INSTALLED_APPS.
1. Add 'crispy_forms' to INSTALLED_APPS and add CRISPY_TEMPLATE_PACK = 'bootstrap4' to your settings.py

**Comment by RamezIssac** [comment]
Hello @Chocrates ... I did double check,,, i couldn't replicate the issue.
Only when i removed `slick_reporting` from `INSTALLED_APPS`.

**Comment by Chocrates** [comment]
Hey @RamezIssac yeah it was user error.  
The [Installation](https://github.com/ra-systems/django-slick-reporting#installation) section only mentions doing a `pip install` but to users with more django experience than me, it should be obvious that adding it to the `INSTALLED_APPS` section is required.

**Comment by RamezIssac** [comment]
Yeah, it's also here https://django-slick-reporting.readthedocs.io/en/latest/#installation
