### ISSUE TITLE
Cant use SlickReportField for FloatField

### ISSUE THREAD

**Issue by nquang2448** [ra-systems/django-slick-reporting#21]
i try use SlickReportView and in
   columns = [
                SlickReportField.create(method = Sum, field= 'balance', name='sum__balance'),
            ]
- field balance is FloatField. They have error :

Exception Type: | KeyError
Exception Value: | 'balance__sum'

![Screen Shot 2021-01-14 at 18 28 38](https://user-images.githubusercontent.com/44407463/104585251-5bca4d80-5696-11eb-96dd-12d1f35da249.png)

**Comment by RamezIssac** [comment]
Can you attach your whole view ?
Looks to me that there is a typo though... in the columns you're showing it is 'sum__balance'.. however the error value you reported cit complains about `balance__sum'

**Comment by nquang2448** [comment]
> Can you attach your whole view ?
> Looks to me that there is a typo though... in the columns you're showing it is 'sum__balance'.. however the error value you reported cit complains about `balance__sum'
> 
> Also: Changing the Decimal Fields to Floats in the tests suits does NOT produce any errors :)

I try find your trouple in your code. I find a line in helpers.py
return '__'.join([calculation_field.lower(), calculation_method.name.lower()])
if my field is : balanceValue
it will return : balancevalue__sum instead of balanceValue__sum
So that's make me have a error.
i try fix it to :
    return '__'.join([calculation_field, calculation_method.name.lower()])
   -> it's solved
