### ISSUE TITLE
Complete Demo App

### ISSUE THREAD

**Issue by dgurovich** [ra-systems/django-slick-reporting#22]
It would be helpful to have a complete django project with working examples, like the ones in the demo for download so I could run it through my IDE and understand it completely.  Your examples are great, I just like to see how the whole things integrates and ties together.

Can you add a full project to your docs?

**Comment by RamezIssac** [comment]
Example app like this one https://github.com/ra-systems/slick-reporting-demo ? :))

**Comment by dgurovich** [comment]
Thanks!

**Comment by RamezIssac** [comment]
My pleasure
