### ISSUE TITLE
NameError: name 'SlickReportField' is not defined

### ISSUE THREAD

**Issue by vinhouw** [ra-systems/django-slick-reporting#27]
I have read the documentation and followed the tutorials. I cannot find my answer.

'slick_reporting' is in installed_apps, I am importing the class correctly, but im still getting the error that it is not defined. 

 thank you

**Comment by jrutila** [comment]
Could you show the relevant code/file that causes the error?

**Comment by vinhouw** [comment]
```
class TimeSeries(SlickReportView):
              report_model= Item
              date_field = 'lastOrdered'
              group_by = 'location'
             columns = ['name]
       
             time_series_columns = [
                    SlickReportField.create(method=Sum, field='quantity', name='quantity__sum', verbose_name= _('Quantities Sold'))
                   ]
```

workspace\inventory_management\inventory\views.py", line 301, in TimeSeries
    SlickReportField.create(method=Sum, field='quantity', name='quantity__sum', verbose_name=_('Quantities Sold'))
**NameError: name 'SlickReportField' is not defined**

It is a pretty basic Class Item model. So i'm not sure why SlickReportField is not recognized.

**Comment by jrutila** [comment]
Your example is still missing the import for SlickReportField. And the columns array is missing a single quotation mark.

**Comment by vinhouw** [comment]
For the column array, i have the correct quotation marks put in my code. I didn't copy and paste from my original window, my bad.
My original thought was the import, but i did not see anywhere in the tutorials where to import it from, therefore my confusion.

**Comment by jrutila** [comment]
Yes, that should do it.
I think this issue should now be about updating the documentation to include the import line.

**Comment by RamezIssac** [comment]
Hello .. I added the missing import to the readme and docs. 
Hint me if you see any other missing.

Have a great day !
