### ISSUE TITLE
templates and static missing when doing pip install

### ISSUE THREAD

**Issue by JEDuRam** [ra-systems/django-slick-reporting#3]
<img width="251" alt="Screen Shot 2020-06-06 at 9 53 14 PM" src="https://user-images.githubusercontent.com/23719706/83945905-39d73580-a840-11ea-9302-58a4a926a67e.png">
The templates and static are missing once I did a pip install, how can I fix this?

**Comment by RamezIssac** [comment]
Thanks a lot @JEDuRam :)
It's fixed now. make sure you install version 0.2.6.
