### ISSUE TITLE
if a group_by is active, then the value of columns are empty

### ISSUE THREAD

**Issue by ovt00** [ra-systems/django-slick-reporting#32]
Hi.
If my report settings is:
        report = ReportGenerator(report_model=Price,
                                 date_field='date',
                                 group_by='product_id',
                                 columns=[
                                     'product_name',
                                     SlickReportField.create(method=Sum, field='quantity_int', name='quantity'),
                                 ],
                       )
  I take result is:
  data = report.get_report_data()
[
  {
    "product_name": "",
    "quantity": 200
  }
]
But, if:
        report = ReportGenerator(report_model=Price,
                                 date_field='date',
                                 # group_by='product_id',
                                 columns=[
                                     'product_name',
                                     SlickReportField.create(method=Sum, field='quantity_int', name='quantity'),
                                 ],
                       )
          and result:
          [
  {
    "product_name": "1",
    "quantity": ""
  }
]
So product_name is empty with group_by

**Comment by barbarakr** [comment]
I think in line https://github.com/ra-systems/django-slick-reporting/blob/2ee433a05eac4b6a875c67619effa8b5f88114f6/slick_reporting/generator.py#L254 the mainqueryset has to include the requested columns like this: 
```
final_fields = list(set(self.get_database_columns() + [self.group_by_field_attname]))
self.main_queryset = self.main_queryset.distinct().values(*final_fields)
```
