### ISSUE TITLE
default rows to show in report

### ISSUE THREAD

**Issue by dgurovich** [ra-systems/django-slick-reporting#33]
I've spent some time combing through the docs, but I don't see where I can set the default number of rows to show when creating a DataTable.  It always defaults to 10 rows.  I saw the limit_rows attribute, but that just limits the number of rows in total, not what I'm looking for.  

Just want to show 25 at a time and paginate....

**Comment by RamezIssac** [comment]
Hello, i believe this a function of datatable plugin itself...
You can change how it is instantiated `$('table').DataTable();`
