### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by giant995** [ra-systems/django-slick-reporting#37]
Is it possible to introduce i18n ourselves while using this library? If so, is it possible to have some pointers on how to achieve it? I would gladly update your documentation afterward with an how-to. Thank you

**Comment by RamezIssac** [comment]
Hello @giant995 , 
Can you give me a use case ?
The package itself does not have any strings in its own

**Comment by giant995** [comment]
I'm coding a platform for a client and it's in french.So I wanted to know if we could provide our own translations for the labels of the filter, for example. I hope I'm clear enough in my request.

**Comment by barbarakr** [comment]
Just add translations to your django locale file and compile messages:
```
# translations for Django Slick Reporting
msgid "Week"
msgstr "Woche"
```
