### ISSUE TITLE
Multiple unrelated report models?

### ISSUE THREAD

**Issue by SilverStrings024** [ra-systems/django-slick-reporting#39]
I need to make a dashboard that has some general data just as an overview. Even though we can declare multiple charts, it looks like we aren't able to include more than one model in one single view. We *can* use cross tab but the models have to be related in that scenario and, while that is a useful thing, it's not something I can do for this use case scenario.

Am I overlooking something or is there really no way to have it make multiple reports for one view?
If this isn't a thing yet, I can try to submit a PR when I have the time to work on it.

Thanks for making the package, it's very useful!

**Comment by RamezIssac** [comment]
Hello there , 

For the dashboard page where you need many different unrelated data, you have two options i believe.
1. in the front end of the dashboard call each view via js and load each chart as the results come. (Prefered)
2. Fall back to ReportGenerator which have the same syntax as the view and add your reports data to the dashboard view context. (suitable if you have like handful of reports data to add)

In both cases you can use the slick reporting js helpers for ChartJS and Highcharts.

Hope i did answer your question .

**Comment by SilverStrings024** [comment]
> Hello there ,
> 
> For the dashboard page where you need many different unrelated data, you have two options i believe.
> 
> 1. in the front end of the dashboard call each view via js and load each chart as the results come. (Prefered)
> 2. Fall back to ReportGenerator which have the same syntax as the view and add your reports data to the dashboard view context. (suitable if you have like handful of reports data to add)
> 
> In both cases you can use the slick reporting js helpers for ChartJS and Highcharts.
> 
> Hope i did answer your question .

Thank you very much for the response!
Yes, it seems like this would work; I'm in the middle of finishing up an analytics system integration so I can't test it right now but I'll post back here if it does work out.
