### ISSUE TITLE
doc_date

### ISSUE THREAD

**Issue by boatpy** [ra-systems/django-slick-reporting#4]
I cannot use slick-reporting without adding doc_date to my model that i wish to report on.  I dont know if this is a bug or intended.  It is not referred to in the documentation and this has been arrived at after hours of trying to troubleshoot why doc_date was required.

**Comment by FredrickUghimi** [comment]
Experiencing same issue with doc_date. Is doc_date intended or a bug?

Slick-Reporting looks really promising.

**Comment by RamezIssac** [comment]
Hello @FredrickUghimi @boatpy 

For the doc_date, the class needs a base date field to work on... it's called 'doc_date' by default .
But you can certainly use another date fields.

**Comment by RamezIssac** [comment]
doc_date reference is removed from code base totally.
if date_field is not set, an exception is raised.

**Comment by FredrickUghimi** [comment]
Great news I guess.

**Comment by FredrickUghimi** [comment]
Hello, I decided to give django-slick-reporting a trial again. I am still
getting errors. The report engine isn't recognising my table fields.

>>doc_date reference is removed from code base totally.
if date_field is not set, an exception is raised.

What date_field? Is it an internal field name that must be used? Or the
name of my date field? My date field name is date. Can I use that?

Kind regards

**Comment by RamezIssac** [comment]
It's nice that you're trying Django Slick Reporting again :)

date_field is the name of date field on your report model that you want to use to filter or in a time series. It's mandatory.

> My date field name is date. Can I use that?

Yes ! `date_field = 'date'`  should do it :)

**Comment by FredrickUghimi** [comment]
Hello,

Thank you for your quick response.

Like i said earlier. I like the django-slick-reporting concept and I really
hope it works well for me.

I have the following issues.

1. I generally have issues with tables having foreignkey. I get the
TypeError ___str___ returned non-string...

2. The date range still doesn't work for me. The report engine date format
is 11/25/2020 and my date format is 2020-11-25. Is that an issue? I tried
entering both format without success.

3. Still haven't seen how to make the chart work.

Kind regards.

**Comment by RamezIssac** [comment]
1. A stack trace would be nice so i can debug

2. I saw couple of issues with dates, they are addressed in the develop branch now.. Pypi release is sometime tomorrow.

3. Charts should be straight forward 

`chart_settings = [{
        'type': 'pie',
        'data_source': ['__total_quantity__'],
        'title_source': ['title'],
    }]`

https://django-slick-reporting.readthedocs.io/en/latest/tour.html#charts 
I welcome any clarification you see regarding the documentation

**Comment by FredrickUghimi** [comment]
Hello,

Thank you for your response.

1. I will send a stack trace later today. I am cleaning up my program.

2. Thank you for your efforts

3. Do I need to do anything to call up the chart? Because I tried the reporting a stand alone table which was successful apart from the date issue, but saw no chart. Is it because I muted the group_by field (since it keeps spitting out error that I can't understand). Is the group_by supposed to point to a field or table? In the chart settings. Is the 'title_source': 'title', just an arbitrary string or a field? The 'title': _('Total Monthly Sales'),':  has an underscore before the open bracket. Is that supposed to be?Because Python is raising an error there. This is confusing:
data_source': '__total_quantity__', Is it point to a normal field or an internal parameter? I used my 'quantity' field.
           
I think publishing a little workable complete sample would suffice and give clarity.

Best regards.

**Comment by gamesbook** [comment]
Re No.3:

For `_`, this is a Django convention (https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#standard-translation):

```
from django.utils.translation import ugettext_lazy as _
```

**Comment by RamezIssac** [comment]
For the chart:

`data_source` parameter : this is the name of the field you want to plot.
In case of having a group_by then that's a ReportField , 
In case of no group_by then it's a field on the report model

A Complete Sample example looks like this 

```python
from django.db.models import Sum
from .models import SalesLineTransaction

class TotalProductSales(SlickReportView):
    report_model = SalesLineTransaction
    report_title = 'Product Sales'
    date_field = 'date'

    # A foreign key to group the calculation on.
    group_by = 'product'
    # the SalesLineTansaction example model have a foreign key called 'product'

    columns = ['title',
               SlickReportField.create(Sum, 'quantity', name='quantity__sum'),
               SlickReportField.create(Sum, 'value', name='value__sum')
               ]

    chart_settings = [{
        # this chart will plot the quantity sum
        'type': 'pie',
        'data_source': ['quantity__sum'],
        'title_source': ['title'],
    }, {
        # this chart will plot the value sum
        'type': 'pie',
        'data_source': ['value__sum'],
        'title_source': ['title'],
    }, 
]

```
If you dont have a group and you want to plot a field on the report model you can definitely do so.

**Comment by FredrickUghimi** [comment]
Hello Ramez,

Thank you for your explanation and the sample codes. It made things a little clearer for me. I was able to successfully create two different charts. One with the group_by included and the other, a standalone table.

My Observations:

1. I don't see the quantity being summed up.
2. The standalone table chart wouldn't display. It says undefined besides the color pallet. The sum values not displaying as well.

Overall things are looking good.

**Comment by RamezIssac** [comment]
Closing
You can always refer to https://django-slick-reporting.com/ for live examples :)

**Comment by FredrickUghimi** [comment]
Hello!

This is really great. Great job!

Like i said earlier I like the concept of django-slick-reporting. It is my
number one choice for django projects.

Is the date range reporting issue fixed? Can we now generate chart on one
model (model not connected to any other model, no group by)?

Kind regards.

**Comment by RamezIssac** [comment]
You can generate a chart on a model not connected to any other model .. that's for sure.
You can also do reports without the group by (like in here https://django-slick-reporting.com/time-series-without-group-by/)

Kind regards.

**Comment by FredrickUghimi** [comment]
Great example. Thank you.

**Comment by FredrickUghimi** [comment]
Hello Ramez,

I am trying to the use the time series link you provided.

What does this stand for? col

columns = ['__time_series__',

Is time_series supposed a field or is it an internal function? Runs on my
local server, but Heroku has issues with it: From Heroku:

django.core.exceptions.FieldDoesNotExist: Field "__time_series__" not found
either as an attribute to the generator class <class
'slick_reporting.generator.ReportGenerator'>, or a computation field, or a
database column for the model "<class
'paymentreceived.models.TblPaymentReceived'>"

My chart doesn't plot even on my local server:

Here is my Model:

from django.db import models
from datetime import datetime
from django.urls import reverse
from biodata.models import TblBioData
from patientcategory.models import TblPatientCategory


Cmethod = models.TextChoices('Cmethod',
'Cash Cheque Transfer Credit_Card POS')

class TblPaymentReceived(models.Model):
    datecreated = models.DateField(default=datetime.now, blank=False)
    hospitalno = models.ForeignKey(TblBioData, on_delete = models.CASCADE)
    surname = models.CharField(max_length=20)
    othernames = models.CharField(max_length=30)
    category = models.ForeignKey(TblPatientCategory, on_delete=models.
CASCADE)
    receiptno = models.CharField(max_length=30)
    method = models.CharField(max_length=20, choices=Cmethod.choices )
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=
0.00)
    purpose = models.CharField(max_length=60)
    cashier = models.CharField(max_length=35)

    def __str__(self):
            return self.hospitalno

    class Meta:
        db_table = 'tblpaymentreceived'
        ordering = ['datecreated']

    def get_absolute_url(self):
        return reverse('paymentreceived:paymentreceived-detail', kwargs={
'pk': self.pk})


My View:

class PaymentReceivedReport(LoginRequiredMixin, SlickReportView):
    report_model = TblPaymentReceived
    date_field = 'datecreated'
    columns = ['__time_series__',
               SlickReportField.create(Sum, 'amount', verbose_name=
'Grand Total')
               ]

    time_series_pattern = 'monthly'
    time_series_columns = [
        SlickReportField.create(method=Sum, field='amount', name=
'amount__sum', verbose_name=_('Amount Received'))
    ]

    # A chart for our total values
    chart_settings = [
        {'type': 'bar',
         'data_source': ['amount__sum'],
         'title_source': ['amount'],
         'title': 'Total Payment Received Per Month',
         'plot_total':True,
         }
    ]

I think adding Models to your sample codes will bring more clarity.

----------------------------------------------------------
Fredrick Ughimi
President, Mega-Net Software Ltd
@MegaNetSoftware, @FrerickUghimi
07035682478, 08050359974
*Website:* www.meganetsoft <http://www.meganetsoft.com>ware.com
<http://ware.smemarkethub.com>



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by RamezIssac** [comment]
I think slick-reporting version on heroku version is outdated ...
For the chart,
1. what engine are you using, Charts js or highcharts ? 
2. Please locate the developer tools log on the browser, it might gives an insight on what might be wrong

> I think adding Models to your sample codes will bring more clarity.
Models of different structure you mean ? Can you further explain ?

**Comment by FredrickUghimi** [comment]
Hello,

>>I think slick-reporting version on heroku version is outdated ...

That was my thinking. I updated my requirements.txt file. I thought that
should fix it?

>>For the chart,

what engine are you using, Charts js or highcharts ?

I didn't know one could choose between the two. I thought the the report
engine only works with Chart.js. see my code. I essentially copied your
time_series sample codes. How do you choose.


Please locate the developer tools log on the browser, it might gives an
insight on what might be wrong.

OK. I would try to do that.


>>I think adding Models to your sample codes will bring more clarity.
>>Models of different structure you mean ? Can you further explain ?


What I mean is that for instance the time_series sample code should have an
accompanying model. That will make it easy to differentiate the fields and
internal functions in the sample codes you provide. Again, for instance
this statement:
field='value', name='value__sum'.

Is value actually a table field or an internal function?. I can only guess
its a numeric field. Its better know than guessing.

**Comment by FredrickUghimi** [comment]
I am diligently going through django-slick-reporting.com website . I can
see the report model now. Great. Sorry I didn't see this earlier.

**Comment by FredrickUghimi** [comment]
Hello,

I observed that when I set Debug = False I get a Server Error on the
time_series report using the local server. So its not just Heroku.

About 3 days ago I tried updating my django-slick-reporting installation
and it didn't work so I uninstalled django-slick-reporting and installed
the latest version. I am using Windows System. I checked the developer
tools on Chrome, no error was shown.

Best regards.

**Comment by FredrickUghimi** [comment]
Hello,

I removed and created a new venv and all the dependencies in the project. I
started the local server and was surprised to get the same error message.

Next I disabled all my django-slick-reporting replated codes, removed
django-slick-reporting from the settings and uninstalled
django-slick-reporting. The project started working normally.

I guess you need to look into django-slick-reporting.

Kind regards.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by RamezIssac** [comment]
Glad to know that finally your project is working :)
Closing this.
