### ISSUE TITLE
Overriding the form

### ISSUE THREAD

**Issue by toddmickel** [ra-systems/django-slick-reporting#41]
Hello,

The documentation on overriding the form is pretty scarce.  Specifically, I'm trying to figure out how to override the form to allow me to choose the filter options.  The default behavior of filtering off all the Foreign Keys provides filtering options that don't make sense for my application.

Thank you!

**Comment by RamezIssac** [comment]
Hello Todd
Sorry for the late reply ... 
Yes the details on having a custom form is a bit scarce indeed 
https://django-slick-reporting.readthedocs.io/en/latest/the_view.html#override-the-form

did you manage to do it or not yet ?

**Comment by ajwombat007** [comment]
Hi Ramez,
Only a little way into my journey in django and coding in general but I have got your reporting up and running in my Django App. I have read the 'override the form doco' but I can't wrap my head around it. Are you able to share some more details, sorry? I am wanting to make a number of reports so looking for a way to remove most of the filtering fields within views.py. 
Your other post about the queryset was brilliant as I have a 'multi org' environment and needed to only return data from the users org_id account.
So an answer to this question should see me up and running.
Really appreciate the help, especially for a new coder like myself.
Thanks,
Andrew

**Comment by RamezIssac** [comment]
This in a How to guide on how to override the form 

https://django-slick-reporting.readthedocs.io/en/latest/howto/index.html#customize-the-form
