### ISSUE TITLE
Django 4.0 compatibility

### ISSUE THREAD

**Issue by squio** [ra-systems/django-slick-reporting#42]
Django 4.0 beta is released and this release removes a few deprecated features.

- Utility `force_text` was removed in favor of `force_str` 
- Utility `ugettext_lazy` was removed in favor of `gettext_lazy` 

```
ImportError raised when trying to load 'slick_reporting.templatetags.slick_reporting_tags': 
  cannot import name 'force_text' from 'django.utils.encoding' (.../django/utils/encoding.py)
```

**Comment by RamezIssac** [comment]
Thank you !!
