### ISSUE TITLE
simple time series chart example?

### ISSUE THREAD

**Issue by ayushin** [ra-systems/django-slick-reporting#44]
This looks like a great package, I was trying to create a simple chart, dates (time series) in the X axis and values (counts of different fields) on the Y axis and I don't seem to be able to do that easily?

Surely I am doing something wrong as this is as basic as you can get?

**Comment by RamezIssac** [comment]
Hello ! 
Would this give you a good place to start: https://django-slick-reporting.com/time-series-charts/ ?
