### ISSUE TITLE
Calculate some value, for an interval of time to determine

### ISSUE THREAD

**Issue by Ahmadix** [ra-systems/django-slick-reporting#46]
Hello,
I have an issue in the calculator of value, for an interval of time.
![Capture d’écran de 2021-12-09 22-08-52](https://user-images.githubusercontent.com/78018078/145479796-d1302e96-af66-4d2f-a246-7958f9b8f367.png)
![Capture d’écran de 2021-12-09 22-17-03](https://user-images.githubusercontent.com/78018078/145479828-d53d9af0-2349-49bc-aaf6-b5cf8e1f7a78.png)

the problem is in the 01 of each month, always it is calculates with the previous month
see photos attached for example 12/01/202, is calculated with the month of November
Thanks

**Comment by RamezIssac** [comment]
Hmmm ... i'll check... 
A test case would be appreciated though!

**Comment by RamezIssac** [comment]
Caught on tests & fixed... releasing soon .
Thanks !

**Comment by Ahmadix** [comment]
thank you very much for this wonderful tool ^^
