### ISSUE TITLE
pip install django_slick_reporting gets outdated commit

### ISSUE THREAD

**Issue by ASG09** [ra-systems/django-slick-reporting#47]
I'm using `pip install django_slick_reportng==0.6.2` but pip is not bringing the latest commit "Upgrade in is_ajax check" (so I keep having an error from this ajax check). Am I using pip in a wrong way or does pip takes some time (or action) until this latest commit is incorporated?

An observation: I've noticed the commit "Version 0.6.2" was merged before this "Upgrade in is_ajax check" commit. Maybe I'm wrong but it might indicate a need for a new version for this change to take action on `pip install`

**Comment by RamezIssac** [comment]
Correct .... the newer version is not released yet which contained the is_ajax change for Django 4... very soon.

**Comment by RamezIssac** [comment]
https://github.com/ra-systems/django-slick-reporting/releases/tag/v0.6.3 ;) (y)
