### ISSUE TITLE
group_by in SampleReportView

### ISSUE THREAD

**Issue by boatpy** [ra-systems/django-slick-reporting#5]
Sample report view works if you do noting other than list the model you are reporting on, once you have altered the model by adding the doc_date field.  If you try to do any thing useful like grouping on a foreign key as shown in the documentation, it starts falling apart.

So, if I have a two models a and b and b has a foreign key relation to a then if I want to group data in b based on the key in a, all the fields in b can no longer be found and are flagged up as not found.  The only way to render the template, is to remove all the fields from b and to replace them with fields from a.  At this point you no longer have the report you wanted.

Furthermore, none of the filters at the top of the report actually filter the report.  Upon clicking the button nothing happens to the report.  The only way to get some filtering is to type something into the search field so that the results can filter what is shown.

I have sent you detailed emails about this.

**Comment by mswastik** [comment]
+1 getting same issue, attached screenshot
![Screenshot_20201004_094141](https://user-images.githubusercontent.com/7689061/95031744-34e29f80-06d5-11eb-9560-7d838865197c.png)

**Comment by FredrickUghimi** [comment]
>>Furthermore, none of the filters at the top of the report actually filter the report. Upon clicking the button nothing happens to the report. The only way to get some filtering is to type something into the search field so that the results can filter what is shown.

My experience too.

**Comment by RamezIssac** [comment]
@FredrickUghimi The filter button is fixed (as of v 0.2.9, released earlier today https://pypi.org/project/django-slick-reporting/0.2.9/)
@mswastik The OneToMany Rel is also fixed (as of 0.2.8)

Please feel free to re-open this issue if not fixed., or open another when you find other issues.

Have a wonderful day!
