### ISSUE TITLE
aggregation, totals etc.. 

### ISSUE THREAD

**Issue by boatpy** [ra-systems/django-slick-reporting#6]
Settling for a simple totals report, i tried using the __total_field__ as shown in the documentation, but this also fails.  

Field "__total_field__" not found as an attribute to the generator class, nor as computation field, nor as a database column for the model "modelname"

is what i get.  It would seem that it treats the whole thing as a field rather than a function.

Given the above i have not tried the other functions of slick_reporting,  such as crosstab etc..  You have asked me to post the issues here in order to expedite its resolution.

**Comment by FredrickUghimi** [comment]
Ditto.

**Comment by RamezIssac** [comment]
Hello , 
I apologize for replying this late.
I didn't get how you use the total_field... can you show me a code or something ?
