### ISSUE TITLE
 django tempaltes 

### ISSUE THREAD

**Issue by ahmed-devolper6** [ra-systems/django-slick-reporting#60]
you need to add on readme file how to use the package on django tempalte because i now know how to use it but how to get the report on template im stack it on that

**Comment by RamezIssac** [comment]
Can  you elaborate a little where you're stuck ?
What do you mean by use the package on django  template ?

**Comment by durantsmedia** [comment]
At the moment there is no documentation on how to use the views as a template with a context i.e. we want to be able to integrate the functionality into an existing site with a template e.g.     
using - return render(request, 'dashboard/dashboard.html')

**Comment by RamezIssac** [comment]
Hello @ahmed-devolper6 @durantsmedia 

There is now a page in the docs for addressing how to integrate slick reporting in your design 
https://django-slick-reporting.readthedocs.io/en/latest/topics/integrating_slick_reporting.html
Also, there is now a demo project in the package where you can see it in action.

Let me know if you need more support or if something is not clear.
