### ISSUE TITLE
Demo Website not working

### ISSUE THREAD

**Issue by krishnaw14** [ra-systems/django-slick-reporting#62]
Hi, I cannot access your demo website at https://django-slick-reporting.com/ 

When will it be up again?

<img width="1216" alt="Screenshot 2023-05-09 at 18 17 28" src="https://github.com/ra-systems/django-slick-reporting/assets/25587339/4b702146-b1a2-462c-a628-e6cd7a76334a">

**Comment by RamezIssac** [comment]
Yes server is down, mal update that killed the grub :-/ 
I'm working on it , 
That's the demo repo if you want to check locally https://github.com/ra-systems/slick-reporting-demo

**Comment by RamezIssac** [comment]
Site is back Up :muscle: :tada:

**Comment by krishnaw14** [comment]
Thank you for the quick response!
