### ISSUE TITLE
Incorporating report within a django template

### ISSUE THREAD

**Issue by krishnaw14** [ra-systems/django-slick-reporting#63]
Hi, 

Thank you for your great work. I had a question. 

I am using your report and rendering it with a class-based view as stated in the example in [demo website (simple filter)](https://django-slick-reporting.com/no-group-by/). The report looks great.

I already have a website and I am looking to incorporate your report within that website. My website has a header and footer so I want the report to be displayed between the headers and footer. Can I add a django template code like `{% extends 'base.html' %}` somewhere in SlickReportView class or can I display the report within `{% block content %} {% endblock %} ` or is there a way to render the report inside my already defined Django template?

**Comment by RamezIssac** [comment]
Yeah .. SlickReprotView is a FormView child , and so you have a `template_name` which you can set (among other FormView/CBV properties and methods)

You can check the slick reporting templates https://github.com/ra-systems/django-slick-reporting/tree/develop/slick_reporting/templates/slick_reporting , you can code then in your project , customize them to as you want.

**Comment by krishnaw14** [comment]
Thank you for your reply. I understand. I will try to do that.
