### ISSUE TITLE
Errors following through the Quickstart example

### ISSUE THREAD

**Issue by hnhegde** [ra-systems/django-slick-reporting#69]
Hello folks,

I am following the [example provided in the quickstart guide](https://django-slick-reporting.readthedocs.io/en/latest/index.html#quickstart) and hit some syntax errors straight away. Has anyone else come across this?

```
method=Sum, field="value", name="value__sum", verbose_name=_("Total sold $")
NameError: name 'Sum' is not defined. Did you mean: 'sum'?
```

did I miss anything obvious?
Pycharm is showing me the following suggestions:

![image](https://github.com/ra-systems/django-slick-reporting/assets/4962589/c0ce05ad-2c62-47a3-8503-b576257521ae)

![image](https://github.com/ra-systems/django-slick-reporting/assets/4962589/e6e8e932-4ef6-4f11-8d3b-eb1d0b297cf2)

```
>>> django.VERSION
(4, 1, 6, 'final', 0)
>>> 
```

edit: corrected hyperlink

**Comment by LerikG** [comment]
I believe the example in the quickstart guide is missing an import statement:

`from django.db.models import Sum`

Try adding this to your code.

**Comment by hnhegde** [comment]
[Submitted a PR with this fix and some](https://github.com/ra-systems/django-slick-reporting/pull/70/).
