### ISSUE TITLE
Chart not Appearing when Doing Time Series Tutorial

### ISSUE THREAD

**Issue by MichaelOC05** [ra-systems/django-slick-reporting#73]
Hi I am looking to use django-slick-reporting in an application. 

I am currently using python 3.9.4, Django 4.2.3.

I was going along with the Time Series tutorial found here: https://django-slick-reporting.readthedocs.io/en/latest/tutorial.html#time-series-reportshttps://django-slick-reporting.readthedocs.io/en/latest/tutorial.html#time-series-reports.

However, I was getting the correct values within the table but the chart was not being created. Do you have any idea what the issue could be?

This is the output I am getting.
![2023-08-28 11_48_59-Django Slick Reporting](https://github.com/ra-systems/django-slick-reporting/assets/99509073/6cfa7c93-9a8e-4caa-bf24-979165d6a1e4)

**Comment by MichaelOC05** [comment]
Thank you for getting back to me so quickly, I updated the code as now shown on the tutorial page.

I am getting the following error now:

![image](https://github.com/ra-systems/django-slick-reporting/assets/99509073/a9808023-2163-4ca1-a15a-d1005922811c)

Do you have an idea what could be causing this?

**Comment by RamezIssac** [comment]
https://assets.highcharts.com/errors/16#:~:text=This%20is%20caused%20by%20including,js%20file%20is%20required.

Looks like there is a link to the highcharts.js twice .
Can you double check the js scripts on the page ?

**Comment by MichaelOC05** [comment]
I was able to track it down to line 23 in the js_resources.html file "<script src="https://code.highcharts.com/highcharts.js"></script>". I removed the line and am no longer see the first error, however I am still getting the second error.

![image](https://github.com/ra-systems/django-slick-reporting/assets/99509073/7f4b59b4-c1fb-444e-ac83-f8043debc379)

**Comment by RamezIssac** [comment]
The error says now that there is no Highcharts on the page :-)
I'll re-check the js resources.

**Comment by RamezIssac** [comment]
I believe i got the issue, There is some work in progress on the branch "feature/demo_app" if you want to check it out.

Will merge and release in the upcoming day(s)

**Comment by MichaelOC05** [comment]
Thank you

**Comment by willunicamp** [comment]
Same issue here.

**Comment by RamezIssac** [comment]
Good day @MichaelOC05 , @willunicamp 
There is a new release available https://pypi.org/project/django-slick-reporting/1.0.2/
Also now the documentation section was revisied from the tutorial, group by and time series documentation 
and finally there is a demo app now on the repo .

Let me know if the new release / documentation solve your problems.
Best

**Comment by willunicamp** [comment]
> Good day @MichaelOC05 , @willunicamp There is a new release available https://pypi.org/project/django-slick-reporting/1.0.2/ Also now the documentation section was revisied from the tutorial, group by and time series documentation and finally there is a demo app now on the repo .
> 
> Let me know if the new release / documentation solve your problems. Best

It worked! Thank you very much!
