### ISSUE TITLE
Printing Report

### ISSUE THREAD

**Issue by FredrickUghimi** [ra-systems/django-slick-reporting#8]
Hello, 

How do you print the report generated by django-slick-reporting? I don't see a print button on the generated report or do I have to improvise?

Best regards.

**Comment by RamezIssac** [comment]
Hello ..
For printing, i believe yes, you'd to improvise. At least for now .

**Comment by FredrickUghimi** [comment]
Hello Ramez 

>>For printing, i believe yes, you'd to improvise. At least for now .

Thank you for your response.

I like the idea behind Django-Slick-Reporting. Please keep up the good work.

Best regards.
