### ISSUE TITLE
chartjs not working with new slick reporting templates

### ISSUE THREAD

**Issue by oaaoaa** [ra-systems/django-slick-reporting#80]
The latest (v 1.1.0) report.html and widget_template.html don't have the canvas required by chartjs.

**Comment by RamezIssac** [comment]
Noted, will adjust the slick_reporting.chartjs to create one

**Comment by RamezIssac** [comment]
Hello 
The fix is now released https://pypi.org/project/django-slick-reporting/1.1.1/

Demo for chartjs Charts:

https://django-slick-reporting.com/chartjs-examples/
