### ISSUE TITLE
font awesome version mismatch in v 1.1.0 

### ISSUE THREAD

**Issue by oaaoaa** [ra-systems/django-slick-reporting#81]
For chart selector font awesome tags are being used by slick reporting. The latest version v 1.1.0 is generating using the v5 font awesome syntax whereas the v4 font awesome has been included in the templates. There doesn't appear to be a standard cdn for font awesome v5 onwards. So the best is for the developer to specify the url for the font awesome kit as a settings which can then be included in the templates.

**Comment by RamezIssac** [comment]
Hello @oaaoaa 

Thank you for the issue report and the suggestion.
I will be adding a setting for specifying the font awesome url And a map 
ir Line chart = 'fa line' etc depending on the version .

Wil do that as soon as possible.

**Comment by RamezIssac** [comment]
Hello 
The fix is now released https://pypi.org/project/django-slick-reporting/1.1.1/

For customization and changing the FONT_AWESOME mapping
https://django-slick-reporting.readthedocs.io/en/latest/ref/settings.html
