### ISSUE TITLE
Reporting with no date filters?

### ISSUE THREAD

**Issue by helmetwearer** [ra-systems/django-slick-reporting#82]
I'm not understanding why a date field must always be present to do a report?

https://github.com/ra-systems/django-slick-reporting/blob/develop/slick_reporting/generator.py#L269

While date filters are convenient why is it that every example always includes a date? Seems very flawed to assume that all datasets we're going to report on include a date and it's very not obvious how to turn this behavior off if there even is a way

**Comment by RamezIssac** [comment]
This package originated from a business and financial reporting need which always implied the existence of a date field (when a transaction or event happened) 
and hence also the need of its existence in the filter form at all times.

Can you give me an example of a dataset without any date?

**Comment by helmetwearer** [comment]
Sure, an example would be one of these:
https://docs.djangoproject.com/en/4.2/topics/db/models/

And then just don't use one of these:
https://docs.djangoproject.com/en/4.2/ref/models/fields/#datefield
https://docs.djangoproject.com/en/4.2/ref/models/fields/#datetimefield

And there you have a dataset without a datefield.

Also here's chatgpt answering the question:
https://drive.google.com/file/d/1hqWsyVjHNJmqIkJAoOOEOToP_Qucl084/view

**Comment by RamezIssac** [comment]
Links to documentation and a Chatgbt answer ?!
I find this to be rude and condensending.

**Comment by helmetwearer** [comment]
You marked the serious design flaw as a question showing that there was no easy fix to this poor assumption the whole project is based off, as well as 0 intent to fix. Then you proceeded to ask an incredibly stupid question to which there are infinite permutations of answers.

I find that dismissive and condescending so you got a response in kind to how you approached it.
