### ISSUE TITLE
ReportViewBase.get_form_kwargs should add "request" to the kwargs

### ISSUE THREAD

**Issue by oaaoaa** [ra-systems/django-slick-reporting#88]
Since in the example provided in docs for customization of SlickReportForm.__init__ request is passed as one of the params it will help to have a custom filter form based on the request if request is added to the kwargs of the form

Please change ReportViewBase.get_form_kwargs to:

```
    def get_form_kwargs(self):
        """
        Returns the keyword arguments for instantiating the form.
        """
        kwargs = {
            "initial": self.get_initial(),
            "prefix": self.get_prefix(),
            "request": self.request,   #### Add this ####
        }
        ...
```

**Comment by RamezIssac** [comment]
Thank you.
But' it's the argument in the form that needs to be removed. Done.

**Comment by RamezIssac** [comment]
I understand your point... i almost did that but for the basic documentation, I thought better to keep it the point.
Maybe i can add this scenario in an example in a "how to" document or something.
