### ISSUE TITLE
DataTables warning message 

### ISSUE THREAD

**Issue by monicobr** [ra-systems/django-slick-reporting#90]
Hi there. I just installed Slick-reporting. But when I want to use it the following popup windows appears: 

![datatablewarning](https://github.com/ra-systems/django-slick-reporting/assets/47458991/aeb3e79d-c097-4791-ac76-6e6fadda8aac)

Any idea how to fix it 
Thanks in advance.

**Comment by RamezIssac** [comment]
Can you give me more details ?
This is the demo_project ?
There might be an error on the django console... if so can you share it ?

Thank you

**Comment by monicobr** [comment]
Hi, I ran it, again. Django console message is in the following line:
06/Oct/2023 19:26:57] "GET /static/slick_reporting/slick_reporting.js HTTP/1.1" 304 0
Not Found: /favicon.ico
[06/Oct/2023 19:26:57] "GET /product-sales/?start_date=2023-01-01%2000%3A00%3A00&end_date=2023-10-06%2019%3A26%3A53 HTTP/1.1" 200 830

I hope this helps

**Comment by monicobr** [comment]
BTW. I found the Django warning message: Warning: slick_reporting.view.SlickReportView and slick_reporting.view.SlickReportViewBase are deprecated in favor of slick_reporting.view.ReportView and slick_reporting.view.BaseReportView
  class SalesReport(SlickReportView):
System check identified no issues (0 silenced).

**Comment by monicobr** [comment]
pip freeze of the Dango project

asgiref==3.7.2
crispy-bootstrap4==2022.1
Django==3.2.22
django-crispy-forms==2.0
django-slick-reporting==1.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
simplejson==3.19.2
six==1.16.0
sqlparse==0.4.4
typing_extensions==4.7.1

**Comment by nunombispo** [comment]
I noticed that with django-slick-reporting==1.0.2 this error doesn't happen.

**Comment by RamezIssac** [comment]
@monicobr Is there any data in the database ?
If not, then you should use `python manage.py create_entries`  to populate the demo project  database.

I will check the issue further on my end.

**Comment by RamezIssac** [comment]
The current develop branch (about to be released) do not have issues on empty database... Can you check that and let me know ?

**Comment by monicobr** [comment]
> I noticed that with django-slick-reporting==1.0.2 this error doesn't happen.

Hi, Nuno. I installed the Slick reporting version above and  It worked smoothly ! Thanks

**Comment by monicobr** [comment]
> The current develop branch (about to be released) do not have issues on empty database... Can you check that and let me know ?

Hi, Ramez. I appreciate a lot your time to help to solve this Slick Reporting issue. I installed Slick Reporting 1.0.2 version and it worked smoothly. I attached a screenshot of it.
![slickreporting](https://github.com/ra-systems/django-slick-reporting/assets/47458991/a02c519a-89a5-4425-a9af-09ab1654ce3d)

**Comment by RamezIssac** [comment]
You're welcome
